title: Hello, World! We are Teiex.org # name of the site
author: Paulo Matheus # name of site's author
#email: # email of site's author
url: teiex.org # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Teiex is a acronym of "Technology Invention Experts". 
  We believe that everyone deserves to benefit from the power of technology.

permalink: /:slug.html

favicon: "logo-teiex.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, keep it (remote_theme: riggraz/no-style-please)

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "<<" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
